faturamento = 54000;
cliente12345 = 0;


for (var c = 0; c < 5; c++) {
    let valor = console.log(`Digite o valor da compra do ${c} cliente:`);
} if (faturamento < 5400) {
    console.log (`O faturamento ${faturamento} não atingiu o valor superior a 5400`);
} else if (faturamento > 5400) {
    console.log (`O faturamento de ${faturamento} atingiu o valor superior a 5400`);
    console.log ( `O faturamento foi de ${faturamento - 54000}`);
}